[package]
name = "python-svdata"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "python_svdata"
crate-type = ["cdylib","rlib"]

[dependencies]
pyo3 = "0.18.1"
sv-parser = "0.13.0"
